#!/bin/bash

if [ -L ${BASH_SOURCE[0]} ]
then 
	LINKED=$( readlink "${BASH_SOURCE[0]}" )
	DIR="$( cd "$( dirname "${LINKED}" )" && pwd )"
else
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if [ -d "${DIR}/target" ]
then
	JAR=${DIR}/target/pollock-*-standalone.jar
else
	JAR=./pollock.jar
fi

export DISPLAY=localhost:1.0
Xvfb :1 -screen 0 1152x900x8 -fbdir /tmp &

java -jar $JAR

killall Xvfb
